# fly.toml app configuration file generated for jiujitsu-sistema on 2026-06-09T19:12:48-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'jiujitsu-sistema'
primary_region = 'gru'

[build]

[env]
  DATABASE_URL = 'sqlite:////data/jiujitsu.db'

[[mounts]]
  source = 'jiujitsu_data'
  destination = '/data'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0

[[vm]]
  memory = '256mb'
  cpus = 1
  memory_mb = 256
